name: EnchantmentLockUpd
version: '${project.version}'
main: studio.thelpro.enchantmentlockupd.EnchantmentLockUpd

authors: [Newt, TheLPro]

api-version: '1.20'

permissions:
  el.bypass:
    description: Bypass the lock
    default: op